void main() {
  String black = "Kyrgyzstan";
  String black2 = " beautiful country";
  print(black + black2);
  print(black.length);
  print(black2.length);
  print(black.isEmpty);
  print(black2.isEmpty);
  print(black.toLowerCase());
  print(black2.toLowerCase());
  print(black.toUpperCase());
  print(black2.toUpperCase());
  print(black.trim());
  print(black2.trim());
  print(black.compareTo(black2));
  print(black.replaceAll("Kyrgyzstan", "1"));
  print(black2.replaceAll(" beautiful country", "3"));
  print(black.split(""));
  print(black2.split(""));
  print(black.substring(1));
  print(black.substring(0, 9));
  print(black2.substring(1));
  print(black2.substring(2, 17));
  String black3 = "Window";
  print(black3[0]);
  print(black3[1]);
  print(black3[2]);
  print(black3[3]);
  print(black3[4]);
  print(black3[5]);
  int k = 9;
  print(k.runtimeType);
  print(k.toString().runtimeType);
  List<int> numbers = [11, 0, 4, 62, 32, 99];
  print(numbers);
  print(numbers.first);
  print(numbers.length);
  print(numbers[3]);
  print("numbers.last = ${numbers.last}");
  print(numbers[numbers.length - 1]);
  print(numbers.isEmpty);
  print(numbers.isNotEmpty);
  print(numbers.reversed.toList());
  numbers.sort();
  print(numbers.reversed.toList());
  List<String> persons = ["Petr", "Timur", "Tynchtyk"];
  print(persons);
  persons.add("Jack");
  print(persons);
  persons.addAll(["Alan", "Semen"]);
  print(persons);
  List<String> persons1 = ["tt", "qq"];
  persons.addAll(persons1);
  print(persons);
  persons.insertAll(1, ["duncan", "skillet"]);
  print(persons);
  persons.remove("Petr");
  print(persons);
  persons.removeRange(1, 5);
  print(persons);
}
